# Enables the "Sponsor" button on the repository page.
#
# github: [LiddyLove]          # requires GitHub Sponsors enrollment
ko_fi: LiddyLove 
# buy_me_a_coffee: YOURNAME
# liberapay: YOURNAME
# custom: ["https://example.com/donate"]
